# Site settings
title: Faith Chung
email: chungfaith1@gmail.com
description: "Faith Chung's Digital Portfolio"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/fchung1/
  - title: github
    url: https://github.com/chungfaith1

# Postal address (add as many lines as necessary)
address:
  - line: Boston, MA

# Build settings
markdown: kramdown
permalink: pretty
